### ISSUE TITLE
Model isnt zipkin compatible

### ISSUE THREAD

**Issue by codefromthecrypt** [jcchavezs/zipkin-agent#6]
The model types are not zipkin compatible, with fields undefined in any zipkin format. This is confusing so should be changed to match the model

http://zipkin.io/zipkin-api/#/default/post_spans

**Comment by jcchavezs** [comment]
New model is compliant with the documentation. I will add a new issue for validation of ID and TraceID.

**Comment by codefromthecrypt** [comment]
I agree! thanks for sorting it
